GIZUMO_wiki　タスク２　カテゴリー更新機能の実装
gizumo-inc/gizumo_wiki pull request #248
Opened 2021-07-26 02:58 UTC by masatosi1018

### **変更内容**

①カテゴリー更新機能を追加しました。
②エラーメッセージと完了メッセージが表示される機能を追加しました。
③Vee-validateでインプットエリア内が空文字の際はエラーが表示される処理を追加しました。

### **変更結果**
カテゴリー更新ボタンを押した際に該当するカテゴリー名をinputエリア内に表示することができ、
カテゴリー名を変更し、更新ボタンを押した際にはAPI通信でカテゴリー内容を更新することができました。
さらにエラー文がある際には動的に切り替わるといった処理も記述しました。

2021-07-26 03:14 UTC, kanemototomoki requested changes

2021-07-26 03:14 UTC, kanemototomoki commented on src/js/_store/modules/categories.js
> +      }).then((response) => {
[imo]
分割代入を使えば簡潔にかけるかな！

2021-07-26 03:14 UTC, kanemototomoki commented on src/js/_store/modules/categories.js
> +      data.append('name', this.state.categories.updateCategoryName);
[imo]
`this.state` で直接値を取ってくるより新規でgettersを作成して、getterから値を取るように変更しましょうか！

2021-07-26 03:14 UTC, kanemototomoki commented on src/js/pages/Categories/Edit.vue
> +      return this.$store.state.categories.errorMessage;
[imo]
`mapGetters` を使って簡潔に書きましょうか！
mapGettersが分からなければVuexの公式などに書いてあるので調べてみて下さい！

2021-07-26 03:14 UTC, kanemototomoki commented on src/js/pages/Categories/Edit.vue
> +    this.$store.dispatch('categories/getCategory', id);
[imo]
この辺りも `mapActions` を使って簡潔に記述できます！

2021-07-26 06:49 UTC, masatosi1018 commented
GIZUMO_wikiタスク２　カテゴリー更新機能　修正箇所　修正済み
・分割代入を使用し、無駄な記述を減らしました。
・gettersに新たに値を追加し、その値をaction内で使用し、意図しないdataの書き換えを防ぐ記述をしました。
・mapGettersとmapActionsを使用し、コンポーネントからgettersとactionsを参照できる記述をしました。

2021-07-26 07:17 UTC, kanemototomoki requested changes

2021-07-26 07:17 UTC, kanemototomoki commented on src/js/_store/modules/categories.js
> +        const category = data.category;
ここも分割代入できるよー

2021-07-26 07:17 UTC, kanemototomoki commented on src/js/_store/modules/categories.js
> +        url: `/category/${this.state.categories.updateCategoryId}`,
ここなんでゲッター使ってないの？

2021-07-27 02:07 UTC, masatosi1018 commented on src/js/_store/modules/categories.js
> +        const category = data.category;
### **修正内容**
・指摘された箇所を分割代入で記述しました。
### **修正コミット**
a31f0528590fe55f4db706037c56cb912eff3f7b

2021-07-27 02:10 UTC, masatosi1018 commented on src/js/_store/modules/categories.js
> +        url: `/category/${this.state.categories.updateCategoryId}`,
### **修正内容**
・指摘いただいた点を、gettersを用いて記述しました。
・mapGettersやmapActionを使用し、記述量を減らす変更しました。
### **修正コミット**
a31f0528590fe55f4db706037c56cb912eff3f7b

2021-07-27 02:21 UTC, masatosi1018 commented on src/js/_store/modules/categories.js
> +        const category = data.category;
### **修正内容**
・指摘いただいた箇所を分割代入で記述し、変更を加えました。
### **修正コミット**
ae7f57bb574ac1a35b58abc36777b3d404157711
12a24da3033907a4cd1fe2a03a353852fb1af1ab

2021-07-27 06:34 UTC, kanemototomoki requested changes

2021-07-27 06:34 UTC, kanemototomoki commented on src/js/components/molecules/CategoryEdit/index.vue
> +      this.$emit('clearMessages');
ここって親のイベント名単数系じゃない？

2021-07-27 08:17 UTC, masatosi1018 commented on src/js/components/molecules/CategoryEdit/index.vue
> +      this.$emit('clearMessages');
お疲れさまです。指摘いただいた箇所を確認し、修正しました。
### **修正内容**
メソッド名の変更とclearMessageが重複して記述していたのでそこの削除を行いました。

### **修正コミット**
7cad75c742268d147e67a323296825e242d0fa38

2021-07-27 08:22 UTC, merged